### PR TITLE
Move separators in WLAN attributes, etc.; fix Status typo

### PR DESCRIPTION
**Pull request by DavidCurtiss**
### What does this Pull Request accomplish?

Moves the underscore separators in WLAN attributes, function parameters, and enum values.
Fixes a typo.

### Why should this Pull Request be merged?

Consistency, correctness.
Regen from scrapigen & update tests.

### What testing has been done?

Ran the system tests and the examples.

image

### CODE REVIEW

**Review by astarche — APPROVED** [review]

**Review by reckenro — APPROVED** [review]

**Review by mgumble — CHANGES_REQUESTED** [review]
I would expect there to be a few changes in ofdm-modacc.py.

For example                 frequency_error_estimation_method=nirfmxwlan_types.OFDM_MODACC_FREQUENCY_ERROR_ESTIMATION_METHOD_PREAMBLE_AND_PILOTS,
please run the validate_examples.py to ensure these examples still pass

**Comment by DavidCurtiss** [comment]
> I would expect there to be a few changes in ofdm-modacc.py.

@mgumble Those changes _are_ in the PR, including the specific one you called out. (And I just ran the examples again to be sure.)

**Comment by mgumble** [comment]
Oh not sure how I missed that :/ why did you close this PR?

**Comment by DavidCurtiss** [comment]
> Oh not sure how I missed that :/ why did you close this PR?

Ugh. Misunderstood the button I was clicking.

**Review by mgumble — APPROVED** [review]

**Pull request merged**
