### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by christag-ni**
### What does this Pull Request accomplish?

Bumps the version in CMake file

### Why should this Pull Request be merged?

To accurately reflect the version grpc-device is in

### What testing has been done?

No testing

### CODE REVIEW

**Review by reckenro — CHANGES_REQUESTED** [review]
Marking this to make sure the version is bumped on the AzDo side first so this change doesn't get included in any 2.3 adhoc exports.

**Review by astarche — APPROVED** [review]
Defer to @reckenro. Don't want to block.

**Review by SparkingSpork — APPROVED** [review]
Approved pending what @reckenro already said.

**Review by reckenro — APPROVED** [review]

**Comment by reckenro** [comment]
FYI main is locked as the release is finalized on AzDo / we bump the grpc-device version on the AzDo side for new exports. This should be resolved early next week. Alex, Maxx, or I can then unlock main here in grpc-device after that's all settled.

**Comment by christag-ni** [comment]
Is run_win_system_tests supposed to take this long to find a runner?

**Comment by christag-ni** [comment]
Accidentally clicked on "Close with comment", we're gonna have to wait for builds to complete again. Apologies

**Pull request merged**
