### PR TITLE
codegen: Delete LibraryAndService

### PR DESCRIPTION
**Pull request by bkeryan**
### What does this Pull Request accomplish?

Now that the service object uses `shared_ptr` to share ownership of the library object, we no longer need `LibraryAndService` to ensure that the library object exists for the lifetime of the service object.

### Why should this Pull Request be merged?

This is optional part 4 of a fix for #936

### What testing has been done?

Manually tested DAQmx task leak scenario with the full fix.

### CODE REVIEW

**Comment by bkeryan** [comment]
I used Graphviz to make a diagram showing object ownership:

server_lifetime

Source:
```
// Usage: dot -Tpng server_lifetime.dot -o server_lifetime.png

digraph {
  // register_all_services.cpp
  "core server" -> "session repository";
  "core server" -> "service";
  "session resource repository" [label="session resource\nrepository"];
  "service" -> "session resource repository";
  "session resource repository" -> "session repository";

  // *_service_registrar.cpp
  "service" -> "library";

  // *_service.cpp
  "service" -> "cleanup lambda" [style="dotted" label="creates"];
  "cleanup lambda" -> "library";
  "session repository" -> "cleanup lambda";

  // session_resource_repository.h
  //
  // (This cleanup lambda wraps the service's cleanup lambda, but
  // combine them for the diagram.)
  "cleanup lambda" -> "resource map";
}
```

Would it be reasonable to store the .dot file & the generated .png in the wiki, or would it make more sense to check them into the repo?

**Comment by astarche** [comment]
@bkeryan Personally I like putting this sort of thing in `source` (like under a `docs` or `specs` folder). But the most similar thing in `grpc-device` is the [Internal Development wiki[(https://github.com/ni/grpc-device/wiki/internal-development). So, either way is fine by me, but going with the wiki is more consistent.

**Review by astarche — APPROVED** [review]
Thanks for taking this on and for putting in the effort to stage the changes intuitively!

**Review by reckenro — APPROVED** [review]

**Comment by bkeryan** [comment]
> @bkeryan , I agree with Alex that I think starting from a clean slate I'd prefer it in source like in specs or docs folder but as things are I think it makes sense somewhere in the [Internal Development section of the wiki](https://github.com/ni/grpc-device/wiki/internal-development).

I added it to the wiki: https://github.com/ni/grpc-device/wiki/Server-Design

It turns out that GitHub supports [Mermaid](https://mermaid.js.org/), which are a Markdown-inspired diagram markup language, so the diagram source is embedded in the wiki page.

**Pull request merged**
