### PR TITLE
Copy localhost server config file to binary directory.

### PR DESCRIPTION
**Pull request by csjall**
### What does this Pull Request accomplish?

Currently we are copying insecure server configuration file to artifact directory. Copy localhost server configuration file to artifact directory.

### Why should this Pull Request be merged?

This will restrict server to localhost connections by default. Users now have to update address and security fields in order to allow remote connections.

### What testing has been done?

Launch server with new default configuration.

### CODE REVIEW

**Review by SparkingSpork — CHANGES_REQUESTED** [review]
Have you checked with NI-Sync about these changes? The server is used by them on NI Linux RT and I have a feeling that it's going to be a bad customer experience if they have to manually change this for every RT target they have. 

I'm also concerned installers exist for Windows that it's not obvious to customers that they have to do extra configuration work to get things working for the remote case.

**Comment by csjall** [comment]
> Have you checked with NI-Sync about these changes? The server is used by them on NI Linux RT and I have a feeling that it's going to be a bad customer experience if they have to manually change this for every RT target they have.

I was under the impression that NI-Sync has their own server configuration file with a custom port number. I will double check.

**Comment by csjall** [comment]
> I'm also concerned installers exist for Windows that it's not obvious to customers that they have to do extra configuration work to get things working for the remote case.

I have raised similar concerns in [discussion thread](https://teams.microsoft.com/l/message/19:658a48f1bcd240dc9c56f5eb35761898@thread.tacv2/1668029353375?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=22cecbce-4450-4339-bbf5-85ade50ab7fb&parentMessageId=1668029353375&teamName=gRPC&channelName=grpc-device&createdTime=1668029353375&allowXTenantAccess=false). Most folks agreed that we should put safety/security first.

**Review by SparkingSpork — APPROVED** [review]

**Review by astarche — APPROVED** [review]

**Comment by astarche** [comment]
Marked as `breaking-change` so it will show up in the list for the release notes.

**Review by reckenro — APPROVED** [review]

**Comment by reckenro** [comment]
Note: You can ignore the one failing test on the `run_win_system_tests` step. I filed #791 to look into and address it. I've seen it pop up intermittently for a while now.

**Pull request merged**
