### PR TITLE
Updated grpc device code for ModSpectrum APIs and Attributes

### PR DESCRIPTION
**Pull request by Udeepchandra**
What does this Pull Request accomplish?
Updates niRFmxBT in grpc-device to 24.3
Updates the Grpc Device Code for Mod spectrum APIs and attributes.
Updates the Grpc Device Code for Channelsoundingsyncsequence attribute enum update to payload pattern

Why should this Pull Request be merged?
Updated to match the upcoming release of niRFmxBt 24.3.0

What testing has been done?
Manually inspected generated files..
Manually inspected nirfmxbluetooth.proto file

### CODE REVIEW

**Review by reckenro — CHANGES_REQUESTED** [review]
Same question as on the corresponding scrapigen PR: Is this to match an upcoming RFmx BT release? Typically we bump the metadata to match a new version of the API (see [last bump to 24.0](https://github.com/ni/grpc-device-scrapigen/pull/204)).

And if so, you'll want to update the version in [config.py](https://github.com/ni/grpc-device/blob/cbf3f281529daa68036e8f27863358697199f09b/source/codegen/metadata/nirfmxbluetooth/config.py#L3) and the README to be up to date.

**Comment by Udeepchandra** [comment]
This will match the Upcoming RFmx 24.3 BT Release.

**Review by reckenro — CHANGES_REQUESTED** [review]
Can you update [config.py](https://github.com/ni/grpc-device/blob/cbf3f281529daa68036e8f27863358697199f09b/source/codegen/metadata/nirfmxbluetooth/config.py#L3) and the [README](https://github.com/ni/grpc-device/blob/main/README.md) to bump the RFmx BT version to 24.3?

**Comment by Udeepchandra** [comment]
> Can you update [config.py](https://github.com/ni/grpc-device/blob/cbf3f281529daa68036e8f27863358697199f09b/source/codegen/metadata/nirfmxbluetooth/config.py#L3) and the [README](https://github.com/ni/grpc-device/blob/main/README.md) to bump the RFmx BT version to 24.3?

Updated the Version.

**Review by reckenro — APPROVED** [review]
Looks good. FYI there's a [Bug](https://dev.azure.com/ni/DevCentral/_workitems/edit/2640696) right now preventing submission in the repo (it's what's causing the validate_python step to fail). You'll have to wait for that to go in before getting a passing build and ability to merge.

**Review by astarche — APPROVED** [review]

**Comment by Udeepchandra** [comment]
> Looks good. FYI there's a [Bug](https://dev.azure.com/ni/DevCentral/_workitems/edit/2640696) right now preventing submission in the repo (it's what's causing the validate_python step to fail). You'll have to wait for that to go in before getting a passing build and ability to merge.
> 
> Update: That bug was fixed but I think you'll have to merge main to get those fixes into this branch and the CI build to pass.



> Looks good. FYI there's a [Bug](https://dev.azure.com/ni/DevCentral/_workitems/edit/2640696) right now preventing submission in the repo (it's what's causing the validate_python step to fail). You'll have to wait for that to go in before getting a passing build and ability to merge.
> 
> Update: That bug was fixed but I think you'll have to merge main to get those fixes into this branch and the CI build to pass.

The Python Validation step is now passed Successfully. Looks like the CI/build_desktop/Windows Build Required step failed.

**Comment by reckenro** [comment]
> The Python Validation step is now passed Successfully. Looks like the CI/build_desktop/Windows Build Required step failed.

Oh sorry, I should've mentioned this when you updated `config.py`. It'll cause the .proto to be updated with that new version at the top of the file. So you'll need to rebuild locally and push up the changed .proto file so the build doesn't complain about a mismatch between what's in the branch's generated folder and what the CI build produces.

**Comment by Udeepchandra** [comment]
@maxxboehme Can you review this PR as this PR is being hold from long time because your review is pending on this

**Review by maxxboehme — APPROVED** [review]

**Pull request merged**
