### PR TITLE
Add functions for NI RFmx Demod by updating metadata

### PR DESCRIPTION
**Pull request by ayesham-729**
### What does this Pull Request accomplish?

This PR updates the metadata for NI RFmx Demod with exported files from grpc-device-scrapigen.

### Why should this Pull Request be merged?

Updates grpc-device with some additional functions in NI RFmx Demod

### What testing has been done?

Demod system tests are passing

image

### CODE REVIEW

**Comment by ayesham-729** [comment]
The one failing test in the Ubuntu system tests is for NI-FGEN. Is that something that needs to be addressed?

image

**Comment by reckenro** [comment]
> The one failing test in the Ubuntu system tests is for NI-FGEN. Is that something that needs to be addressed?
> 
> image

No, I think I've seen that one pop up before. Just didn't create an Issue for it before. Tracking it here: https://github.com/ni/grpc-device/issues/951

Unrelated to your changes so no need to worry about it. We have a few intermittent tests noted in the Issues/Bugs.

**Comment by reckenro** [comment]
Note: The code_readiness for RFmx Demod is still marked as NextRelease: https://github.com/ni/grpc-device/blob/50d365b5b3401c7c048c8761e25b4b131dd8912e/source/codegen/metadata/nirfmxdemod/config.py#L30

That should be changed to Release when you want the service enabled by default

**Review by reckenro — APPROVED** [review]

**Comment by shastriUF** [comment]
> Note: The code_readiness for RFmx Demod is still marked as NextRelease: https://github.com/ni/grpc-device/blob/main/source/codegen/metadata/nirfmxdemod/config.py#L30
> 
> That should be changed to Release when you want the service enabled by default

@ayesham-729 I pushed a change just now that changes the codereadiness to Release

**Comment by shastriUF** [comment]
Demod tests passed in the CI build, seems to have run into an unrelated timeout
image

**Comment by reckenro** [comment]
> Demod tests passed in the CI build, seems to have run into an unrelated timeout image

Yeah, I saw it pass the Demod tests on that run so it should be fine. Added an Issue though to bump that timeout, I think we've just finally hit the limit we set initially for these Windows system tests: https://github.com/ni/grpc-device/issues/952

**Pull request merged**
